services:
  - type: web
    name: mysql-docker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 1234
      - key: MYSQL_DATABASE
        value: work
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: 1234
    ports:
      - 3306
